version: '3.8'
services:
  psqldb:
    image: postgres:14.4
    restart: unless-stopped
    #env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$PSQL_ROOT_PASSWORD
      - POSTGRES_USER=$PSQL_USER
      - POSTGRES_DB=$PSQL_DATABASE
    ports:
      - $PSQL_LOCAL_PORT:$PSQL_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
<<<<<<< HEAD
    network_mode: bridge
=======
    networks:
      - backend
>>>>>>> parent of 737abb0 (Update docker-compose.yaml)
  
  webapp:
    depends_on:
      - psqldb
    build: 
      context: ./webapp
      args:
        - DB_HOST=psqldb
        - DB_USER=$PSQL_USER
        - DB_USER_PW=$PSQL_ROOT_PASSWORD
        - DB_NAME=$PSQL_DATABASE
        - DB_PORT=$PSQL_DOCKER_PORT
    restart: unless-stopped
<<<<<<< HEAD
    network_mode: bridge
    
=======
    networks:
      - backend

>>>>>>> parent of 737abb0 (Update docker-compose.yaml)
  nginx:
    image: nginx:latest
    depends_on:
      - webapp
    ports:
      - $LOCAL_PORT:80 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
<<<<<<< HEAD
    network_mode: bridge
volumes: 
  db:
=======
    networks:
      - backend
volumes: 
  db:
networks:
  backend:
>>>>>>> parent of 737abb0 (Update docker-compose.yaml)
